### ISSUE TITLE
Get Firefox add-on signed

### ISSUE THREAD

**Issue by charleseff** [jordwest/news-feed-eradicator#12]
The Firefox add-on no longer worked for me because Firefox blocks unsigned add-ons.  Can you get this add-on signed so that we can all continue to enjoy it?  Thanks!

**Comment by xxdavid** [comment]
There is a workaround – go to `about:config` and set `xpinstall.signatures.required` to false.

**Comment by charleseff** [comment]
Ah that works, thanks!

**Comment by bradmont** [comment]
While this works short-term, every time firefox updates it deactivates the add-on. Would it be possible to get it signed and maybe uploaded to addons.mozilla.org?

**Comment by xxdavid** [comment]
@jordwest, the next version of Firefox (46) will completely disallow to install unsigned extensions. It would be really great if you could [submit](https://addons.mozilla.org/en-US/developers/addon/submit) this extension to [AMO](https://addons.mozilla.org/en-US/firefox/). It should take maximally 15 minutes and it doesn't cost anything (like Chrome Web Store).
Few months ago I did the same with my addon. AMO has to manually review the addon before publishing. My addon was initally rejected because I bundled it with Webpack (like you) and they don;t like it. This is what I had to do to get it accepted:
1. Submit the addon
2. `npm shrinkwrap` so they can do a diff with the same dependencies
3. Go to My Submissions, select Manage Status & Versions in the left sidebar, click your version
4. Add a zip with the source code
5. Insert something like this to Notes for reviewers:

> This extension uses third party libraries that are bundled together using Webpack. You can view the original source in the attached zip (or at https://github.com/xxdavid/lastfm-friends-who-listen/tree/v1.0). If you don't believe me that I haven't changed the bundled code or libraries, you can build it for yourself:
> 1. remove dependencies (rm -rf node_modules/)
> 2. install them again from source (npm install)
> 3. remove built code (rm -rf build)
> 4. install Gulp if you don't have it (npm install -g gulp)
> 5. build it again (gulp build)

That should be enough.

**Comment by jordwest** [comment]
Oh nice, thanks for that tip @xxdavid! I did submit it months ago and it was rejected for the reason you mentioned. I'll give it another go when I find some time.

**Comment by t-p-tan** [comment]
In the meantime I got it working by using Firefox Developer's Edition instead

**Comment by jordwest** [comment]
I'm going to look into this again when I have time next.

In the meantime, @bogas04 mentioned having success using [Chrome Store Foxified](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/) to install the extension.

**Comment by figurehe4d** [comment]
As someone who relied on this plugin heavily (in chrome) for productivity, I would really like to know what the status on this is. Part of my work day involves posting content and managing pages on fb, the news feed acts as a tractor beam for attention, certainly it's designed to be this way and it does it's job well!

**Comment by bs** [comment]
Yes, please. Desperately need this!

**Comment by milsto** [comment]
I can confirm that it works perfectly when installing it from [Chrome Store Foxified](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/). The process is simple and it has no infinite reloading problem.

**Comment by olegantonyan** [comment]
Hi
Any news on publishing it to addons.mozilla.org?

**Comment by banool** [comment]
Any progress on this? The [Chrome Store Foxified](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/) solution works, but a native solution would obviously be better.

**Comment by jordwest** [comment]
I'm working on simplifying the build output to make the review process easier before submitting it to addons.mozilla.org again.

**Comment by jordwest** [comment]
The latest version is finally available on the Firefox Add-On store!

https://addons.mozilla.org/en-US/firefox/addon/news-feed-eradicator/
