### ISSUE TITLE
Newsfeed Eradicator Stopped Working on Facebook

### ISSUE THREAD

**Issue by AMLucht** [jordwest/news-feed-eradicator#243]
Newsfeed eradicator stopped working on facebook. Seems to be working fine on other sites. Tried uninstalling and reinstalling but it didn't work.

**Comment by NonlethalGhost** [comment]
Same, it is working on everything except facebook.

**Comment by AprilMason0101** [comment]
It isn't working on Facebook, agree. Once in a while it will work again and then stop again.

**Comment by Dunkalot** [comment]
Same with mine, initially worked by reopening tab, but now it fails every time.

**Comment by flutefish** [comment]
Same here!

**Comment by direrFlood** [comment]
Newsfeed Eradicator Stopped Working on Facebook same as me

**Comment by Afterstone** [comment]
I can confirm having this issue too.

**Comment by RileySeaburg** [comment]
Can confirm

**Comment by nzawirski** [comment]
This issue is a duplicate of #232  The changes are being rolled out for different people at different times and it seems like a new wave just started. I just got the update as well and it stopped working for me too. After quick research i see that their DOM is an absolute mess, it's might be tricky to figure out how to fix this for this update.

**Comment by AMLucht** [comment]
The issue is now resolved on my end. Happy to get back to work and not get stuck in a Facebook scroll!
