### ISSUE TITLE
Any way this plug in can eventually be used for Facebook's mobile site?

### ISSUE THREAD

**Issue by pclaradactyl** [jordwest/news-feed-eradicator#35]
Deleting the app doesn't break my habit of opening the mobile site in chrome, which the plug in doesn't work for. 

My brother needs to access Facebook on his phone for school related groups he needs to check on, but he doesn't want the newsfeed either. Having the ability to block the newsfeed on on phones would be wonderful.

**Comment by elkirkmo** [comment]
AFAIK, chrome extensions aren't supported on mobile chrome. I am going to take a stab at this functionality anyway, because, as you mentioned, one can simply change www.facebook.com to m.facebook.com and get their newsfeed back. Hopefully when (if) google allows extensions on mobile chrome it'll port over as is.

**Comment by jordwest** [comment]
Unfortunately it's not possible (yet) to distribute any sort of common extension for mobile browsers

**Comment by drmercer** [comment]
This probably wasn't true when this issue was last considered, but NFE can currently be installed on Firefox for Android. Sadly it doesn't work, since it doesn't affect m.facebook.com, but it should be possible to enhance the add-on to work for mobile Facebook, too. Please reconsider this issue!
