### ISSUE TITLE
Will news-feed-eradicator work with the new facebook UI?

### ISSUE THREAD

**Issue by FelDev** [jordwest/news-feed-eradicator#80]
Once again, a new UI is just around the corner for facebook and it's already available.

![Screen Shot 2019-10-20 at 2 08 00 PM](https://user-images.githubusercontent.com/17578204/67163921-0b552a80-f343-11e9-879c-c0de0ad2fe9c.png)
(click on the little arrow and find "facebook beta")

I'm just wondering if support for the upcoming UI is already on the roadmap for news-feed-eradicator? 

<br>
<br>
(Thanks for this awesome extension, by the way. 👏)

**Comment by piotrenewicz** [comment]
Came here to ask the same question. 

This new facebook UI now features a "dark mode", and looks rather great.
Facebook is now notifying users about the existance of this beta mode; 
making it seem like they're getting close to rolling it out.

I'm sticking with the old UI, because of the news-feed-eradicator support. 
Really can't get by without it working.  (Thanks for this extension, it's an essential tool)

I'm waiting on a notification from this thread. 
With hope that the author has the capacity to work on this extension, before facebook decides it's time to ditch the old UI.

**Comment by PeterMitrano** [comment]
If you set up a donation badge, I'm sure you get some money to make this update worth your time.

**Comment by jordwest** [comment]
Hi yep it's definitely planned, but unfortunately I still haven't been given access to the new Facebook Beta.

If you're able to help though, I'd really appreciate it! I've created an issue with some details: #82 

Will close this issue for now, follow #82 for updates.
